services:
  -     type: web
    name: anime-poster-bot
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
